drop table ALBUM if exists;
drop table HOUSE if exists;
drop table ARTIST if exists;

create table ALBUM (ALBUM_ID bigint generated by default as identity, GENRE varchar(255), NO_OF_SONGS integer, title varchar(255), RELEASE_YR integer, ARTIST_ID bigint, primary key (ALBUM_ID));
create table ARTIST (ARTIST_ID bigint generated by default as identity, NAME varchar(255), primary key (ARTIST_ID));
create table HOUSE (HOUSE_ID bigint generated by default as identity, CITY varchar(255), STREET varchar(255), ZIP varchar(255), ARTIST_ID bigint, primary key (HOUSE_ID));
alter table ALBUM add constraint FK3B7864FC018F8EB foreign key (ARTIST_ID) references ARTIST;
alter table HOUSE add constraint FK41BCF00C018F8EB foreign key (ARTIST_ID) references ARTIST;